### PR TITLE
Project NYT clone

### PR DESCRIPTION
**Pull request by Grifo89**
1.Layout using float, position, grid, and flexbox.
2.Dealing with a complex layout.
3.Dealing with the overlapped images.

### CODE REVIEW

**Review by Ispirett — APPROVED** [review]

**Review by Ispirett — CHANGES_REQUESTED** [review]
Really Excellent work here @Grifo89 @OlukaDenis .

They're just a few bugs :bug: to fix before merging 

Use this tool to fix these issues [tool](https://validator.w3.org/#validate_by_upload)

image

 
#### Important
Please fix the errors and the stickler errors and submit for rereview.
Please use more descriptive commit messages.

**Comment by Grifo89** [comment]
Hey Guys, We've just tried to fix those errors that stickler yields and has been really annoying because every time we fix the errors, stickler doubles the errors, so seriously we are tired to run around and actually this project has been the best that we have done so far.

**Comment by Grifo89** [comment]
@Ispirett We just want to ask you What is your name to put you as a reviewer of our project?

**Review by bolah2009 — APPROVED** [review]
# Awesome job team :clap: 

### It's a :+1: from me.

#### :heavy_check_mark: This project is approved.

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

**Pull request merged**
